//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Fusion
{
		public static class FusedConfiguration
		{
			public enum FusionType {
				FUSION_STANDARD  , // All sensors begining with the upper body (without SpineBase). Can be use for upper body only.
				FUSION_LOWERBODY , // Begining with the SpineBase then the Legs.
				
				// TODO Hands and Feet
			};

			// Our choice
			public static FusionType CurrentFusionType = FusionType.FUSION_STANDARD;//LOWERBODY;
		}
}

